url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 0c7bf42ac2265d13845ffe0c499d16e6b8cdedea
version: 69.8.2-rancher.25
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/prometheus-community/helm-charts.git
      commit: 0c7bf42ac2265d13845ffe0c499d16e6b8cdedea
      subdirectory: charts/kube-prometheus-stack/charts/crds/crds
    crdOptions:
      addCRDValidationToMainChart: true
      templateDirectory: crd-template
      useTarArchive: true
doNotRelease: false
