url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: b93b9d562b01733df25ac266d84c16d562df3b4e
version: 77.9.1-rancher.11
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/prometheus-community/helm-charts.git
      commit: b93b9d562b01733df25ac266d84c16d562df3b4e
      subdirectory: charts/kube-prometheus-stack/charts/crds/files
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: monitoring-crd
doNotRelease: false
