url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 9c2619e6f3650a5722b0f81f18850b3751ce31ba
version: 66.7.1-rancher.5
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/prometheus-community/helm-charts.git
      commit: 9c2619e6f3650a5722b0f81f18850b3751ce31ba
      subdirectory: charts/kube-prometheus-stack/charts/crds/crds
    crdOptions:
      addCRDValidationToMainChart: true
      templateDirectory: crd-template
      useTarArchive: true
doNotRelease: false
